version: '3.3'
services:
  prometheus:
    image: ${USER_NAME}/prometheus
    networks:
      - reddit
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
volumes:
  prometheus_data:
networks:
  reddit:
