---
- name: Configure ruby server 
  hosts: app
  become: true
  vars:
    db_host: 10.132.0.43
  tasks:
    - name: 
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma
    - name: add conf for db conection
      template:
        src: templates/db_config.j2
        dest: /home/ybudnyi/db_config
        owner: ybudnyi
        group: ybudnyi
    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
  handlers:
  - name: reload puma  
    systemd: name=puma state=restarted
